from typing import TypedDict, List, Annotated
from langchain_core.documents import Document
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


# state for the agent
class RAGState(TypedDict):
    query: str
    messages: Annotated[list, add_messages]
    retrieved_docs: List[Document]
    reranked_docs: List[Document]
    response: dict
    generated_sql: str  # sql generated by nl2sql
    route: str  # vector_db or rdbms
    sql_result: str  # output of the raw sql execution result
    images: list
    evaluation: dict
    is_good: bool
    attempts: int
    memory: List[str]
    context: str
    answer: str
    intent: str
